# Generated by Django 3.2.9 on 2021-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfood',
            name='src',
            field=models.TextField(default=' ', verbose_name=' '),
            preserve_default=False,
        ),
    ]
