# Generated by Django 3.2.9 on 2021-11-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('when', models.TextField()),
                ('product', models.TextField()),
                ('total', models.IntegerField()),
                ('status', models.TextField()),
            ],
        ),
    ]
