# Generated by Django 3.2.9 on 2021-11-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidefood',
            name='src',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
